local_backend: false

backend:
  name: github
  repo: cnzixn/my-hugo-site
  branch: main
  auth_type: web  # 必须为 web 模式
  base_url: https://a.bxq.me  # 例如 https://a.bxq.me
  site_domain: https://a.bxq.me  # 同上
  app_id: ${GITHUB_CLIENT_ID}
  api_key: ${GITHUB_CLIENT_SECRET}

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

styles:
  - "/admin/custom.css"  # 指向你的 CSS 文件路径

collections:
  - name: "posts"
    label: "文章页面"
    folder: "content/posts"
    create: true
    extension: "md"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # 推荐使用 Hugo 的 slugify 函数处理标题
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "date", label: "日期", widget: "datetime", format: "YYYY-MM-DD", default: "{{ now }}" }
      - { name: "author", label: "作者", widget: "string", default: "bny" }
      - { name: "tags", label: "标签", widget: "list", default: ["标签1", "标签2"] }
      - { name: "aliases", label: "短链接", widget: "list", required: false }
      - { name: "comments", label: "开启评论", widget: "boolean", default: true }
      - { name: "body", label: "正文", widget: "markdown" }