# baseURL = "https://b.bxq.me"
# relativeURLs = true # 启用相对路径
# canonifyURLs = true # 页面用对决路径
title = ""
theme = "hugo-notepadium"
copyright = "©2025 兔人协会" # <a href='https://github.com/cnzixn/my-hugo-site' >Github</a>


languageCode = "zh-cn"
hasCJKLanguage = true

enableRobotsTXT = true

summaryLength = 9  # Summary Length

defaultContentLanguage = "zh"
[languages.zh]
languageName = "中文"
weight = 1

[outputs]
home = ["HTML", "JSON"]

# [services.disqus]
# shortname = "" # Disqus shortname

# [services.googleAnalytics]
# id = "" # Google tag ID

[Pagination]
pagerSize = 20  # 每页显示文章
path = "page"
disableAliases = false


[markup.highlight]
codeFences = true
noClasses = false
lineNos = true           # 启用行号
lineNumbersInTable = true
# style = "github-dark"    # 选择你喜欢的配色方案



[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown


[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = ""  # if unset, default is "2006-01-02" Monday, January 2, 2006
logo = "http://q1.qlogo.cn/g?b=qq&nk=1163650990&s=100"  # if you have a logo png
slogan = ""  # 100% JavaScript-free
license = "<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1' >CC BY-NC-SA 4.0</a>"  # CC License
fullRss = true # Puts entire HTML post into rss "description" tag. If unset, default is false.
ipv6ready = false # Show IPV6Ready logo on footer.
search = true
# mainSections = ["posts"]

[params.comments]
enable = true  # En/Disable comments globally, default: false. You can always enable comments on per page.

# [params.comments.utterances]
# 暂未使用
# repo = "MetalBlueberry/MetalBlueberry.github.io" # enable comments with [utteranc.es](https://utteranc.es/)
# repo = "cnzixn/utteranc" # enable comments with [utteranc.es](https://utteranc.es/)
# issueTerm = "title"
# label = "评论"
# theme = ""

[params.math]
enable = true  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "mathjax"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "xcode"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.share]
enable = false
addThisId = ""
inlineToolId = ""

[params.nav]
showCategories = false       # /categories/
showTags = false             # /tags/
showBottom = false # article navigation

# custom navigation items
[[params.nav.custom]]
title = "全部"
url = "/posts"

[[params.nav.custom]]
title = "资料"
url = "/tags/资料"

[[params.nav.custom]]
title = "日志"
url = "/tags/日志"

[[params.nav.custom]]
title = "搜索"
url = "/search"

[[params.nav.custom]]
title = "问答"
url = "/faq"

[[params.nav.custom]]
title = "关于"
url = "/about"

# [[params.nav.custom]]
# title = "小店"
# url = "/web-shop/"

# for chinese
[params.beian]
  icp = ""     # example: 粤ICP备20056596号-1
  gongan = ""  # example: 粤公网安备 44030502005645号
  code = ""    # example: 44030502005645


# 其他配置项省略...

# [params.profile]
  # enable = true
  # avatar = "/img/avatar.jpg"  # 假设头像路径是这个，你需要替换为实际路径
  # name = "张三"
  # bio = "张三是一位技术爱好者，对编程和写作有着浓厚的兴趣。"
  # github = "zhangsan-github"
  # docker = "zhangsan-docker"
  # twitter = "zhangsan-twitter"
  # email = "zhangsan@example.com"
