# when using the default proxy server port
# local_backend: true

# This line should *not* be indented
publish_mode: editorial_workflow

backend:
  squash_merges: true
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  open_authoring: true
  commit_messages:
    create: "由 {{author.name }} 创建"
    update: "由 {{author.name }} 更新"
    delete: "由 {{author.name }} 删除"
    uploadMedia: "由 {{author.name }} 上传媒体"
    deleteMedia: "由 {{author.name }} 删除媒体"

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads








# 内容集合配置
collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "时间", name: "date", widget: "datetime"}
      - {label: "作者", name: "author", widget: "string"}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "别名", name: "aliases", widget: "list"}
      - {label: "评论", name: "comments", widget: "boolean"}
      - {label: "内容", name: "body", widget: "markdown"}
    access:
      create: writer, editor, admin
      update: writer, editor, admin
      delete: writer, editor, admin  # 前端代码会细化控制
    workflow:
      states:
        - { label: 草稿, name: draft }
        - { label: 提交审核, name: in_review }
        - { label: 审核通过, name: ready }
        - { label: 公开发表, name: published }

  - name: "pages"
    label: "其他"
    folder: "content"
    create: true
    slug: "{{slug}}"
    access:
      - role: "admin"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "布局", name: "layout", widget: "string", default: "page"}
      - {label: "内容", name: "body", widget: "markdown"}

















