backend:
  name: git-gateway
  branch: main  # 你的Git分支名

# 移除集合内的access配置，保留全局access_control
access_control:
  - role: "writer"
    collection: "posts"
    actions: ["create", "update"]
    status: ["draft"]
  - role: "editor"
    collection: "posts"
    actions: ["read", "update", "delete"]
    status: ["draft", "pending"]
  - role: "admin"
    collection: "*"
    actions: ["*"]
    status: ["*"]


# 媒体文件存储设置
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# 内容集合配置
collections:
  - name: "blog"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    workflow:
      - label: "草稿"
        name: "draft"
        meta: { status: "draft" }
      - label: "待审核"
        name: "pending"  # 统一状态名
        meta: { status: "pending" }
      - label: "已发布"
        name: "published"
        meta: { status: "published" }
    fields:
      - label: "标题"
        name: "title"
        widget: "string"
        default: "文章标题"
        pattern: ['^.{10,100}$', "标题需10-100个字符"]

      - label: "时间"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ssZ"  # ISO 8601格式
        date_format: "YYYY-MM-DD"       # 显示格式
        time_format: "HH:mm:ss"         # 时间显示格式
        default: "2025-02-28T12:00:00Z"

      - label: "作者"
        name: "author"
        widget: "string"
        default: "未知"
        pattern: ['^.{1,50}$', "文章作者需1-50个字符"]

      - label: "标签"
        name: "tags"
        widget: "list"
        default: ["资料"]
        allow_add: true  # 允许添加新标签

      - label: "别名"
        name: "aliases"
        widget: "list"
        default: ["url"]
        allow_add: true  # 允许添加新标签
        required: false

      - label: "评论"
        name: "comments"
        widget: "boolean"
        default: false
        required: false
        hint: "是否允许用户评论此文章"

      - label: "内容"
        name: "body"
        widget: "markdown"

  - name: "generic_pages"
    label: "其他"
    folder: "content"
    create: true
    slug: "{{slug}}"
    access:
      - role: "admin"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "布局", name: "layout", widget: "string", default: "page"}
      - {label: "内容", name: "body", widget: "markdown"}

















