local_backend: true

backend:
  name: git-gateway
  branch: main
  # name: github
  # repo: cnzixn/my-hugo-site
  squash_merges: true
  open_authoring: true
  auth_scope: repo


media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow
# editorial_workflow: true

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "状态", name: "status", widget: "select", options: ["draft", "in_review", "published"]}
      - {label: "标题", name: "title"}
      - {label: "时间", name: "date", widget: "datetime"}
      - {label: "作者", name: "author"}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "短链", name: "aliases", widget: "list"}
      - {label: "评论", name: "comments"}
      - {label: "内容", name: "body", widget: "markdown"}
    create: true
    publish: false  # 普通用户不可直接发布
    workflow:
      - label: "草稿"
        name: "draft"
        delete: true
        transitions:
          - label: "提交审核"
            name: "submit_review"
            to: "in_review"
            roles: ["admin", "editor"]  # 管理员也必须显式提交审核
      - label: "审核中"
        name: "in_review"
        transitions:
          - label: "批准发布"
            name: "approve"
            to: "published"
            roles: ["admin"]  # 仅管理员可最终发布

  - name: "pages"
    label: "其他"
    folder: "content"
    create: true
    publish: false  # 普通用户不可直接发布
    slug: "{{slug}}"
    # access:
      # - role: "admin"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "布局", name: "layout", widget: "string", default: "page"}
      - {label: "内容", name: "body", widget: "markdown"}

















