local_backend: true

backend:
  name: git-gateway
  branch: main
  # name: github
  # repo: cnzixn/my-hugo-site
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title"}
      - {label: "时间", name: "date", widget: "datetime"}
      - {label: "作者", name: "author"}
      - {label: "标签", name: "tags"}
      - {label: "别名", name: "aliases"}
      - {label: "评论", name: "comments"}
      - {label: "内容", name: "body", widget: "markdown"}
    create: true
    # 启用审稿流程(文章页面不会有 Publish 按钮)
    editorial_workflow: true

  - name: "pages"
    label: "其他"
    folder: "content"
    create: true
    publish: false  # 普通用户不可直接发布
    slug: "{{slug}}"
    access:
      - role: "admin"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "布局", name: "layout", widget: "string", default: "page"}
      - {label: "内容", name: "body", widget: "markdown"}

















