local_backend: true

backend:
  name: git-gateway
  branch: main
  # name: github
  # repo: cnzixn/my-hugo-site
  squash_merges: true
  open_authoring: true

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # - {label: "状态", name: "status", widget: "select", options: ["draft", "in_review", "published"]}
      - {label: "标题2", name: "title"}
      - {label: "时间", name: "date", widget: "datetime"}
      - {label: "作者", name: "author", default: "bny"}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "短链", name: "aliases", widget: "list"}
      - {label: "评论区", name: "comments", default: "true"}
      - {label: "内容", name: "body", widget: "markdown"}
    create: true
    # publish: false  # 普通用户不可直接发布
    workflow:
      publish_mode: editorial_workflow  # 确保启用工作流
      filters:
        - label: "Draft"
          name: "draft"
          filter:
            status: "draft"  # 仅显示草稿状态内容
        - label: "In Review"
          name: "in_review"
          filter:
            status: "in_review"  # 仅显示审核中内容
    # 删除或注释掉 "ready" 的配置块 ▼
    # - label: "Ready"
    #   name: "ready"
    #   filter:
    #     status: "ready"

  - name: "pages"
    label: "其他"
    folder: "content"
    create: true
    # publish: false  # 普通用户不可直接发布
    slug: "{{slug}}"
    # access:
      # - role: "admin"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "布局", name: "layout", widget: "string", default: "page"}
      - {label: "内容", name: "body", widget: "markdown"}

















