local_backend: true
locale: "zh" # 语言环境
publish_mode: editorial_workflow

backend:
  name: git-gateway
  branch: main
  # name: github
  # repo: cnzixn/my-hugo-site
  squash_merges: true
  open_authoring: true

# backend:
  # name: github
  # repo: cnzixn/my-hugo-site
  # branch: main

# 角色定义
roles:
  - name: admin
    description: 完全控制所有内容和设置
    permissions:
      collections: ["posts", "pages", "settings"]
      actions: ["create", "edit", "delete", "publish"]

  - name: editor
    description: 可编辑已发布内容，不可删除或发布新内容
    permissions:
      collections: ["posts"]
      actions: ["edit"]
      filters:
        status: "published"

  - name: author
    description: 仅可创建和编辑自己的草稿
    permissions:
      collections: ["posts"]
      actions: ["create", "edit"]
      filters:
        author: "${user.login}"
        status: "draft"


media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # - {label: "状态", name: "status", widget: "select", options: ["draft", "in_review", "published"]}
      - {label: "标题2", name: "title"}
      - {label: "时间", name: "date", widget: "datetime"}
      - {label: "作者", name: "author", default: "bny"}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "短链", name: "aliases", widget: "list"}
      - {label: "评论区", name: "comments", default: "true"}
      - {label: "内容", name: "body", widget: "markdown"}
      - name: "seo_keywords"
        label: "SEO 关键词"
        widget: "string"
        condition:
          role: ["admin"]  # 仅管理员可见
    create: true
    # publish: false  # 普通用户不可直接发布
    # 权限控制
    access:
      create: ["admin", "author"]
      edit: ["admin", "editor", "author"]
      delete: ["admin"]
      publish: ["admin", "editor"]
    publish_mode: editorial_workflow
    workflow:
      branches:
        - label: "草稿"
          name: "draft"
          roles: ["author"]  # 作者只能推送到草稿分支
        - label: "审核"
          name: "review"
          roles: ["editor"]  # 编辑可审核草稿
        - label: "发布"
          name: "published"
          roles: ["admin"]  # 仅管理员可发布

  - name: "pages"
    label: "其他"
    folder: "content"
    create: true
    # publish: false  # 普通用户不可直接发布
    slug: "{{slug}}"
    # access:
      # - role: "admin"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "布局", name: "layout", widget: "string", default: "page"}
      - {label: "内容", name: "body", widget: "markdown"}

















