# /cms-administrator/config.yml

local_backend: true

backend:
  name: git-gateway
  branch: main
  # name: github
  # repo: cnzixn/my-hugo-site
  squash_merges: true
  open_authoring: true

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

# summary
# Available template tags:
# Template tags are the same as those for slug, with the following additions:
# {{dirname}} The path to the file's parent directory, relative to the collection's folder.
# {{filename}} The file name without the extension part.
# {{extension}} The file extension.
# {{commit_date}} The file commit date on supported backends (git based backends).
# {{commit_author}} The file author date on supported backends (git based backends).


collections:
  - name: "posts"
    label: "文章页面"
    folder: "content/posts"  # 内容存储路径
    create: true
    extension: "md"         # 文件扩展名
    # format: "yaml"   # 声明 Front Matter 格式
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # 文件名规则（可选）
    editor:
      preview: false        # 关闭预览，纯文本模式
    fields:
      - name: "body"
        label: "完整内容"
        widget: "markdown"      # 直接编辑整个文件内容
        default: |
          ---
          title: "新文章"
          date: "2025/01/01"
          author: "bny"
          tags: []
          aliases: []
          comments: true
          ---
          
          在此开始撰写正文...

  # - name: "pages"
    # label: "其他页面"
    # folder: "content"
    # create: true
    # slug: "{{file}}"
    # fields:
      # - {label: "保存", name: "file"}
      # - {label: "标题", name: "title", widget: "string"}
      # - {label: "布局", name: "layout", widget: "string", default: "page"}
      # - {label: "内容", name: "body", widget: "text"}
    # publish: false  # 普通用户不可直接发布

  - name: "pages"
    label: "其他页面"
    folder: "content"
    create: true
    extension: "md"
    slug: "{{title}}"
    fields:
      - name: "body"
        label: "Markdown"
        widget: "text"  # 直接编辑整个文件
        default: |
          ---
          title: "新文章"
          ayout: post
          single: true
          ---
          在此开始撰写内容...




