# /cms-administrator/config.yml

local_backend: true

locale: "zh_" # 语言环境

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

backend:
  name: git-gateway
  branch: main
  # name: github
  # repo: cnzixn/my-hugo-site
  squash_merges: true
  open_authoring: true




collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{file}}"
    fields:
      - {label: "保存", name: "file"}
      - {label: "标题", name: "title"}
      - {label: "时间", name: "date", widget: "datetime"}
      - {label: "作者", name: "author", default: "bny"}
      - {label: "标签", name: "tags", widget: "list"}
      # - {label: "短链", name: "aliases", widget: "list"}
      # - {label: "讨论", name: "comments", default: "true"}
      - {label: "内容", name: "body", widget: "markdown"}
    # publish: false  # 普通用户不可直接发布

  - name: "pages"
    label: "其他"
    folder: "content"
    create: true
    # publish: false  # 普通用户不可直接发布
    slug: "{{file}}"
    # access:
      # - role: "admin"
    fields:
      - {label: "保存", name: "file"}
      - {label: "标题", name: "title", widget: "string"}
      - {label: "布局", name: "layout", widget: "string", default: "page"}
      - {label: "内容", name: "body", widget: "markdown"}

















