# /cms-administrator/config.yml

local_backend: true

locale: "zh_" # 语言环境

publish_mode: editorial_workflow

media_folder: /static/img
public_folder: /img

backend:
  name: git-gateway
  branch: main
  # name: github
  # repo: cnzixn/my-hugo-site
  squash_merges: true
  open_authoring: true




collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{file}}"
    fields:
      - {label: "保存", name: "file", default: {{filename}}}
      - {label: "标题", name: "title"}
      - {label: "时间", name: "date", widget: "datetime"}
      # - {label: "作者", name: "author", default: "bny"}
      
      # 自动记录最后编辑者
      - { name: "last_editor", label: "Last Editor", default: "{{user.login}}" }
      # 自动记录创建者
      - { name: "author", label: "Author", default: "{{user.login}}", required: false }
      # - label: "作者"
        # name: "author"
        # widget: "relation"
        # collection: "users"  # 关联用户集合
        # searchFields: ["username", "display_name"]  # 搜索字段
        # valueField: "username"  # 实际存储值
        # displayFields: ["display_name"]  # 界面显示字段
        # required: false
        # default: "bny"  # 默认用户
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "短链", name: "aliases", widget: "list"}
      - {label: "讨论", name: "comments", default: "true"}
      - {label: "内容", name: "body", widget: "markdown"}
    # publish: false  # 普通用户不可直接发布

  - name: "pages"
    label: "其他"
    folder: "content"
    create: true
    # publish: false  # 普通用户不可直接发布
    slug: "{{file}}"
    # access:
      # - role: "admin"
    fields:
      - {label: "保存", name: "file"}
      - {label: "标题", name: "title", widget: "string"}
      - {label: "布局", name: "layout", widget: "string", default: "page"}
      - {label: "内容", name: "body", widget: "markdown"}

  - name: "users"
    label: "用户管理"
    label_singular: "用户"
    folder: "data/"
    extension: "yml"
    identifier_field: "username"  # 用户名作为唯一标识
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "用户名", name: "username", widget: "string", pattern: ["^user_[a-z0-9_-]{3,20}$", "user_xxxxx，3-20位小写字母/数字/-/_"] }
      - { label: "显示名称", name: "display_name", widget: "string", required: false }
      - label: "头像"
        name: "avatar"
        widget: "image"
        media_folder: "/static/img/{{username}}"
        public_folder: "/img/{{username}}"
        choose_url: false
      - label: "个人简介"
        name: "bio"
        widget: "markdown"
        buttons: ["bold", "italic", "link"]
      - label: "社交媒体"
        name: "social"
        widget: "object"
        fields:
          - { label: "GitHub", name: "github", widget: "string", required: false }
          - { label: "Twitter", name: "twitter", widget: "string", required: false }
          - { label: "Email", name: "email", widget: "string", pattern: ["^\\S+@\\S+$", "请输入有效邮箱"] }










