# /cms-administrator/config.yml

local_backend: true

locale: "zh_" # 语言环境

publish_mode: editorial_workflow

media_folder: /static/img
public_folder: /img

backend:
  name: git-gateway
  branch: main
  repo: cnzixn/my-hugo-site
  squash_merges: true
  open_authoring: true


# summary
# Available template tags:
# Template tags are the same as those for slug, with the following additions:
# {{dirname}} The path to the file's parent directory, relative to the collection's folder.
# {{filename}} The file name without the extension part.
# {{extension}} The file extension.
# {{commit_date}} The file commit date on supported backends (git based backends).
# {{commit_author}} The file author date on supported backends (git based backends).


collections:
  - name: "posts"
    label: "文章页面"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # summary: "{{filename}} - {{commit_author}} - {{commit_date}}"
    fields:
      - {label: "标题", name: "title"}
      - {label: "时间", name: "date", widget: "datetime"}
      - {label: "作者", name: "author", default: "bny"}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "短链", name: "aliases", widget: "list", required: false}
      - {label: "讨论", name: "comments", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
    # publish: false  # 普通用户不可直接发布

  - name: "pages"
    label: "其他页面"
    folder: "content"
    create: true
    slug: "{{file}}"
    fields:
      - {label: "保存", name: "file"}
      - {label: "标题", name: "title", widget: "string"}
      - {label: "布局", name: "layout", widget: "string", default: "page"}
      - {label: "内容", name: "body", widget: "markdown"}
    # publish: false  # 普通用户不可直接发布










